# Generated by Django 2.2.2 on 2019-08-03 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Word')),
                ('group', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Adjetivo',
                'verbose_name_plural': 'Adjetivos',
            },
            bases=('common.word',),
        ),
    ]
