# Generated by Django 2.2.1 on 2019-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjectives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjective',
            name='group',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
