# Generated by Django 2.2.1 on 2019-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='group',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
