# Generated by Django 2.2.2 on 2019-08-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('meaning', models.CharField(max_length=100, null=True)),
                ('strokes_count', models.PositiveIntegerField()),
            ],
        ),
    ]
