# Generated by Django 2.2.1 on 2019-05-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='writting',
            field=models.CharField(max_length=500),
        ),
    ]
