# Generated by Django 2.2.1 on 2019-05-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0002_auto_20190503_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
