# Generated by Django 2.2.1 on 2019-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0003_kanji_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='translation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='writting',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
