# Generated by Django 2.2.1 on 2019-05-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0004_auto_20190504_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='translation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='writting',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
