# Generated by Django 2.2.1 on 2019-05-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0005_auto_20190504_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='writting',
            new_name='kanji',
        ),
        migrations.AddField(
            model_name='kanji',
            name='strokes_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
