# Generated by Django 2.2.1 on 2019-05-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0006_auto_20190504_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='translation',
            new_name='meaning',
        ),
    ]
