# Generated by Django 2.2.1 on 2019-05-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
