# Generated by Django 2.2.1 on 2019-05-05 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_word_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='lecture',
        ),
        migrations.AddField(
            model_name='word',
            name='hiragana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='romaji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='kanji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='kanji.Kanji'),
        ),
    ]
