# Generated by Django 2.2.1 on 2019-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190504_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
