# Generated by Django 2.2.2 on 2019-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_word_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
