# Generated by Django 2.2.2 on 2019-06-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190618_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
